export enum ActionType {
    CATEGORIES_REQUEST = "0",
    CATEGORIES_SUCCESS = "1",
    CATEGORIES_REJECT = "2",
    ANIME_BY_CATEGORY_REQUEST = "3",
    ANIME_BY_CATEGORY_SUCCESS = "4",
    ANIME_BY_CATEGORY_REJECT = "5",
    ANIME_DETAILS_REQUEST = "6",
    ANIME_DETAILS_SUCCESS = "7",
    ANIME_DETAILS_REJECT = "8"
}