export default { 
    LOGIN_INPUT_UPDATE: "1",
    PASSWORD_INPUT_UPDATE: "2", 
    LOGIN_REQUEST: "3", 
    LOGIN_SUCCESS: "4", 
    LOGIN_REJECT: "5", 
    CATEGORY_LIST_REQUEST: "6", 
    CATEGORY_LIST_SUCCESS: "7",
    CATEGORY_LIST_REJECT: "8",
    ITEM_LIST_REQUEST: "9",
    ITEM_LIST_SUCCESS: "10",
    ITEM_LIST_REJECT: "11",
    ITEM_REQUEST: "12",
    ITEM_SUCCESS: "13",
    ITEM_REJECT: "14"
};